version: '2'
services:
  eurekaserver:
     image: kaloyan84/tmx-eurekasvr:chapter8
     ports:
         - "8761:8761"
  configserver:
      image: kaloyan84/tmx-confsvr:chapter8
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_PORT: 8761
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
      image: kaloyan84/tmx-zuulsvr:chapter8
      ports:
        - "5555:5555"
      environment:
        PROFILE: "default"
        SERVER_PORT: "5555"
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=p0stgr@s
        - POSTGRES_DB=eagle_eye_local
  licensingservice:
      image: kaloyan84/tmx-licensing-service:chapter8
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        KAFKASERVER_URI:  "kafkaserver"
        ZKSERVER_URI:     "kafkaserver"
        SERVER_PORT:       8080
        ES_PORT:           9200
        DATABASE_PORT:     5432
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        AUTHSERVER_PORT:   8091
        KAFKASERVER_PORT:  2181
        REDIS_PORT:        6379
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
        ENCRYPT_KEY:      "IMSYMMETRIC"
  organizationservice:
      image: kaloyan84/tmx-organization-service:chapter8
      ports:
        - "8085:8085"
      environment:
        PROFILE:          "default"
        KAFKASERVER_URI:  "kafkaserver"
        ZKSERVER_URI:     "kafkaserver"
        SERVER_PORT:       8085
        DATABASE_PORT:     5432
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        AUTHSERVER_PORT:   8091
        KAFKASERVER_PORT:  2181
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
        ENCRYPT_KEY:      "IMSYMMETRIC"
  authenticationservice:
      image: kaloyan84/tmx-authentication-service:chapter8
      ports:
        - "8901:8901"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8901"
        DATABASE_PORT:     5432
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  orgservice-new:
    image: kaloyan84/tmx-orgservice-new:chapter8
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroutes-service:
    image: kaloyan84/tmx-specialroutes-service:chapter8
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  kafkaserver:
      image: spotify/kafka
      ports:
        - 2181:2181
        - 9092:9092